Repository googleapis/python-bigtable, pull requests merged in 2020-06, with the labels that each got.

#46 docs(bigtable): fix inconsistent display_name update
  docs/instance-api.rst
Labels: cla: yes

#47 docs(bigtable): remove missing argument from instance declaration
  docs/instance-api.rst
Labels: automerge, cla: yes

#55 feat: update gapic-generator and go microgen, backups generated api
  google/cloud/bigtable/cluster.py
  google/cloud/bigtable_admin_v2/__init__.py
  google/cloud/bigtable_admin_v2/gapic/bigtable_instance_admin_client.py
  google/cloud/bigtable_admin_v2/gapic/bigtable_table_admin_client.py
  google/cloud/bigtable_admin_v2/gapic/bigtable_table_admin_client_config.py
  google/cloud/bigtable_admin_v2/gapic/enums.py
  google/cloud/bigtable_admin_v2/gapic/transports/bigtable_instance_admin_grpc_transport.py
  google/cloud/bigtable_admin_v2/gapic/transports/bigtable_table_admin_grpc_transport.py
  google/cloud/bigtable_admin_v2/proto/bigtable_instance_admin.proto
  google/cloud/bigtable_admin_v2/proto/bigtable_instance_admin_pb2.py
  google/cloud/bigtable_admin_v2/proto/bigtable_instance_admin_pb2_grpc.py
  google/cloud/bigtable_admin_v2/proto/bigtable_table_admin.proto
  google/cloud/bigtable_admin_v2/proto/bigtable_table_admin_pb2.py
  google/cloud/bigtable_admin_v2/proto/bigtable_table_admin_pb2_grpc.py
  google/cloud/bigtable_admin_v2/proto/common.proto
  google/cloud/bigtable_admin_v2/proto/common_pb2.py
  google/cloud/bigtable_admin_v2/proto/instance.proto
  google/cloud/bigtable_admin_v2/proto/instance_pb2.py
  google/cloud/bigtable_admin_v2/proto/table.proto
  google/cloud/bigtable_admin_v2/proto/table_pb2.py
  google/cloud/bigtable_admin_v2/types.py
  google/cloud/bigtable_v2/__init__.py
  google/cloud/bigtable_v2/gapic/bigtable_client.py
  google/cloud/bigtable_v2/gapic/bigtable_client_config.py
  google/cloud/bigtable_v2/proto/bigtable_pb2.py
  google/cloud/bigtable_v2/proto/data_pb2.py
  synth.metadata
  tests/unit/gapic/v2/test_bigtable_instance_admin_client_v2.py
  tests/unit/gapic/v2/test_bigtable_table_admin_client_v2.py
Labels: cla: yes, context: partial

#56 chore: set Ruby namespace in proto options, use protoc-docs-plugin 0.8.0
  google/cloud/bigtable_admin_v2/proto/bigtable_instance_admin.proto
  google/cloud/bigtable_admin_v2/proto/bigtable_instance_admin_pb2.py
  google/cloud/bigtable_admin_v2/proto/bigtable_table_admin.proto
  google/cloud/bigtable_admin_v2/proto/bigtable_table_admin_pb2.py
  google/cloud/bigtable_admin_v2/proto/common.proto
  google/cloud/bigtable_admin_v2/proto/common_pb2.py
  google/cloud/bigtable_admin_v2/proto/instance.proto
  google/cloud/bigtable_admin_v2/proto/instance_pb2.py
  google/cloud/bigtable_admin_v2/proto/table.proto
  google/cloud/bigtable_admin_v2/proto/table_pb2.py
  google/cloud/bigtable_v2/proto/bigtable.proto
  google/cloud/bigtable_v2/proto/bigtable_pb2.py
  google/cloud/bigtable_v2/proto/data.proto
  google/cloud/bigtable_v2/proto/data_pb2.py
  synth.metadata
Labels: cla: yes, context: full

#58 fix(python): change autodoc_default_flags to autodoc_default_options
  docs/conf.py
  synth.metadata
Labels: cla: yes, context: full

#59 chore: update generated _pb2 files
  google/cloud/bigtable_admin_v2/proto/bigtable_instance_admin_pb2.py
  google/cloud/bigtable_admin_v2/proto/bigtable_instance_admin_pb2_grpc.py
  google/cloud/bigtable_admin_v2/proto/bigtable_table_admin_pb2.py
  google/cloud/bigtable_admin_v2/proto/bigtable_table_admin_pb2_grpc.py
  google/cloud/bigtable_admin_v2/proto/common_pb2.py
  google/cloud/bigtable_admin_v2/proto/common_pb2_grpc.py
  google/cloud/bigtable_admin_v2/proto/instance_pb2.py
  google/cloud/bigtable_admin_v2/proto/instance_pb2_grpc.py
  google/cloud/bigtable_admin_v2/proto/table_pb2.py
  google/cloud/bigtable_admin_v2/proto/table_pb2_grpc.py
  google/cloud/bigtable_v2/proto/bigtable_pb2.py
  google/cloud/bigtable_v2/proto/bigtable_pb2_grpc.py
  google/cloud/bigtable_v2/proto/data_pb2.py
  google/cloud/bigtable_v2/proto/data_pb2_grpc.py
  synth.metadata
Labels: cla: yes, context: full

#60 chore: use GOOGLE_CLOUD_PROJECT and update reads/filters region tags
  samples/hello/main_test.py
  samples/hello/noxfile.py
  samples/hello_happybase/main_test.py
  samples/hello_happybase/noxfile.py
  samples/instanceadmin/noxfile.py
  samples/metricscaler/metricscaler.py
  samples/metricscaler/metricscaler_test.py
  samples/metricscaler/noxfile.py
  samples/quickstart/main_test.py
  samples/quickstart/noxfile.py
  samples/quickstart_happybase/main_test.py
  samples/quickstart_happybase/noxfile.py
  samples/snippets/filters/filter_snippets.py
  samples/snippets/filters/filters_test.py
  samples/snippets/filters/noxfile.py
  samples/snippets/reads/noxfile.py
  samples/snippets/reads/read_snippets.py
  samples/snippets/reads/reads_test.py
  samples/snippets/writes/noxfile.py
  samples/snippets/writes/writes_test.py
  samples/tableadmin/noxfile.py
  samples/tableadmin/tableadmin_test.py
Labels: cla: yes

#63 chore: template updates
  docs/_templates/layout.html
  synth.metadata
Labels: automerge, cla: yes, context: partial
