Repository googleapis/python-bigtable, pull requests merged in 2020-08, with the labels that each got.

#29 docs: document 'row_set' module explicitly
  docs/row-set.rst
  docs/usage.rst
  google/cloud/bigtable/table.py
Labels: cla: yes

#48 docs: update links to reflect new Github org
  docs/client-intro.rst
  docs/data-api.rst
  docs/instance-api.rst
  docs/row-filters.rst
  docs/table-api.rst
  tests/unit/test_row_data.py
Labels: cla: yes

#49 docs: remove indent from snippet code blocks
  google/cloud/bigtable/app_profile.py
  google/cloud/bigtable/batcher.py
  google/cloud/bigtable/client.py
  google/cloud/bigtable/cluster.py
  google/cloud/bigtable/column_family.py
  google/cloud/bigtable/instance.py
  google/cloud/bigtable/policy.py
  google/cloud/bigtable/row.py
  google/cloud/bigtable/row_data.py
  google/cloud/bigtable/row_set.py
  google/cloud/bigtable/table.py
Labels: cla: yes

#81 docs(samples): filter cpu query to get metrics for the correct resources
  samples/metricscaler/metricscaler.py
  samples/metricscaler/metricscaler_test.py
Labels: automerge, cla: yes

#30 feat: add 'Rowset.add_row_range_with_prefix'
  docs/snippets_table.py
  google/cloud/bigtable/row_set.py
  tests/system.py
  tests/unit/test_row_set.py
Labels: cla: yes

#89 tests: drop instance / cluster node counts for quota
  docs/snippets.py
  samples/instanceadmin/instanceadmin.py
  samples/metricscaler/metricscaler.py
  samples/metricscaler/metricscaler_test.py
  tests/system.py
Labels: automerge, cla: yes, testing, type: process

#50 docs: clarify 'Table.read_rows' snippet
  docs/snippets_table.py
Labels: cla: yes

#79 refactor: create base classes
  google/cloud/bigtable/app_profile.py
  google/cloud/bigtable/base_app_profile.py
  google/cloud/bigtable/base_client.py
  google/cloud/bigtable/base_cluster.py
  google/cloud/bigtable/base_column_family.py
  google/cloud/bigtable/base_instance.py
  google/cloud/bigtable/base_row.py
  google/cloud/bigtable/base_row_data.py
  google/cloud/bigtable/base_table.py
  google/cloud/bigtable/client.py
  google/cloud/bigtable/cluster.py
  google/cloud/bigtable/column_family.py
  google/cloud/bigtable/instance.py
  google/cloud/bigtable/row.py
  google/cloud/bigtable/row_data.py
  google/cloud/bigtable/table.py
  noxfile.py
  setup.py
  tests/system.py
  tests/unit/test_client.py
  tests/unit/test_column_family.py
  tests/unit/test_row.py
  tests/unit/test_row_data.py
  tests/unit/test_table.py
Labels: automerge, cla: yes

#99 docs: update docs build (via synth)
  .gitignore
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  synth.metadata
Labels: automerge, cla: yes, context: full

#100 chore: add docfx session to noxfile, normalize
  noxfile.py
Labels: automerge, cla: yes

#93 docs: switch links to client documentation
  docs/instance-api.rst
  docs/row-filters.rst
  docs/table-api.rst
Labels: automerge, cla: yes

#80 docs: add sample for writing data with Beam
  samples/beam/hello_world_write.py
  samples/beam/hello_world_write_test.py
  samples/beam/noxfile.py
  samples/beam/requirements-test.txt
  samples/beam/requirements.txt
Labels: cla: yes

#83 refactor: create test_base_instance
  tests/unit/test_base_instance.py
  tests/unit/test_instance.py
Labels: automerge, cla: yes

#82 refactor: create test_base_client
  tests/unit/test_base_client.py
  tests/unit/test_client.py
Labels: automerge, cla: yes

#84 refactor: create test_base_cluster
  tests/unit/test_base_cluster.py
  tests/unit/test_cluster.py
Labels: automerge, cla: yes

#85 refactor: create test_base_app_profile
  tests/unit/test_app_profile.py
  tests/unit/test_base_app_profile.py
Labels: automerge, cla: yes

#88 refactor: create test_base_table
  tests/unit/test_base_table.py
  tests/unit/test_table.py
Labels: automerge, cla: yes

#91 refactor: create test_base_row
  tests/unit/test_base_row.py
  tests/unit/test_row.py
Labels: automerge, cla: yes

#106 tests: harden 'snippets_table.py' teardown against 429
  docs/snippets_table.py
Labels: cla: yes

#94 refactor: create test_base_column_family
  tests/unit/test_base_column_family.py
  tests/unit/test_column_family.py
Labels: automerge, cla: yes

#90 refactor: create test_base_row_data
  tests/unit/test_base_row_data.py
  tests/unit/test_row_data.py
Labels: cla: yes

#97 refactor: backup base class
  google/cloud/bigtable/backup.py
  google/cloud/bigtable/base_backup.py
  google/cloud/bigtable/base_table.py
  google/cloud/bigtable/table.py
  tests/unit/test_base_table.py
  tests/unit/test_table.py
Labels: automerge, cla: yes

#104 feat: pass 'client_options' to base class ctor
  google/cloud/bigtable/client.py
  setup.py
  tests/unit/test_client.py
Labels: automerge, cla: yes

#98 refactor: create test_base_backup
  tests/unit/test_backup.py
  tests/unit/test_base_backup.py
Labels: automerge, cla: yes

#110 docs: use correct storage type constant in docstrings
  google/cloud/bigtable/cluster.py
  google/cloud/bigtable/instance.py
Labels: automerge, cla: yes

#109 feat: add client_options to base client class
  google/cloud/bigtable/base_client.py
  setup.py
  tests/unit/test_base_client.py
Labels: cla: yes

#114 fix(python_samples): README link fix, enforce samples=True
  samples/README.md
  samples/hello/README.md
  samples/hello_happybase/README.md
  samples/instanceadmin/README.md
  samples/metricscaler/README.md
  samples/quickstart/README.md
  samples/quickstart_happybase/README.md
  samples/snippets/README.md
  samples/tableadmin/README.md
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#117 [CHANGE ME] Re-generated to pick up changes from self.
  docs/conf.py
  google/cloud/bigtable/backup.py
  google/cloud/bigtable/batcher.py
  google/cloud/bigtable/client.py
  google/cloud/bigtable/row.py
  google/cloud/bigtable/row_data.py
  google/cloud/bigtable/row_set.py
  google/cloud/bigtable_admin_v2/gapic/bigtable_instance_admin_client.py
  google/cloud/bigtable_admin_v2/gapic/bigtable_table_admin_client.py
  google/cloud/bigtable_admin_v2/proto/bigtable_instance_admin_pb2.py
  google/cloud/bigtable_admin_v2/proto/bigtable_instance_admin_pb2_grpc.py
  google/cloud/bigtable_admin_v2/proto/bigtable_table_admin_pb2.py
  google/cloud/bigtable_admin_v2/proto/bigtable_table_admin_pb2_grpc.py
  google/cloud/bigtable_admin_v2/proto/common_pb2.py
  google/cloud/bigtable_admin_v2/proto/instance_pb2.py
  google/cloud/bigtable_admin_v2/proto/table_pb2.py
  google/cloud/bigtable_v2/gapic/bigtable_client.py
  google/cloud/bigtable_v2/proto/bigtable_pb2.py
  google/cloud/bigtable_v2/proto/bigtable_pb2_grpc.py
  google/cloud/bigtable_v2/proto/data_pb2.py
  synth.metadata
  tests/unit/test_backup.py
  tests/unit/test_policy.py
  tests/unit/test_table.py
Labels: api: bigtable, cla: yes, context: none
