Repository googleapis/python-bigtable, pull requests merged in 2020-09, with the labels that each got.

#120 chore: readme cleanup
  .repo-metadata.json
  samples/quickstart/README.md
  samples/tableadmin/README.md
Labels: api: bigtable, cla: yes

#16 fix: pass timeout to 'PartialRowsData.response_iterator'
  google/cloud/bigtable/row_data.py
  tests/unit/test_row_data.py
  tests/unit/test_table.py
Labels: cla: yes

#121 chore: auto generated readme updates
  samples/quickstart/README.md
  samples/tableadmin/README.md
  synth.metadata
Labels: api: bigtable, cla: yes, context: none

#133 chore: harden snippet teardowns against ServiceUnavalable
  docs/snippets.py
  docs/snippets_table.py
Labels: automerge, cla: yes

#132 chore: double timeouts for flaky systests
  tests/system.py
Labels: cla: yes

#124 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: api: bigtable, cla: yes

#123 fix: retry if failure occurs on initial call in MutateRows
  google/cloud/bigtable/table.py
Labels: api: bigtable, cla: yes

#134 chore(CI): add snippet bot support (via synth)
  .github/snippet-bot.yml
  .kokoro/populate-secrets.sh
  .kokoro/release/common.cfg
  .kokoro/trampoline.sh
  docs/conf.py
  samples/hello/README.md
  samples/hello_happybase/README.md
  samples/instanceadmin/README.md
  samples/metricscaler/README.md
  samples/quickstart/README.md
  samples/quickstart_happybase/README.md
  samples/snippets/README.md
  samples/tableadmin/README.md
  scripts/decrypt-secrets.sh
  synth.metadata
Labels: api: bigtable, cla: yes

#128 feat: add response status to DirectRow.commit()
  google/cloud/bigtable/row.py
  tests/unit/test_row.py
Labels: api: bigtable, automerge, cla: yes

#141 tests: harden 'test_delete_column_family' against 504
  tests/system.py
Labels: api: bigtable, cla: yes

#144 chore: remove note about editable installs
  CONTRIBUTING.rst
  synth.metadata
Labels: cla: yes, context: full

#146 chore(python): skip reporting coverage for namespace package
  .coveragerc
  synth.metadata
Labels: api: bigtable, cla: yes, context: full

#143 chore: add sync repo settings config
  .github/sync-repo-settings.yaml
Labels: api: bigtable, automerge, cla: yes
