Repository googleapis/python-bigtable, pull requests merged in 2021-02, with the labels that each got.

#200 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: bigtable, cla: yes

#199 chore: Add header checker config to python library synth
  .github/header-checker-lint.yml
  synth.metadata
Labels: api: bigtable, cla: yes, context: full

#205 chore: upstream synth template changes
  MANIFEST.in
  synth.metadata
Labels: api: bigtable, cla: yes, context: partial

#206 docs: update python contributing guide
  CONTRIBUTING.rst
  synth.metadata
Labels: api: bigtable, cla: yes, context: full

#207 chore: add yoshi-python to CODEWONERS
  .github/CODEOWNERS
Labels: api: bigtable, automerge, cla: yes

#182 feat: add keep alive timeout
  google/cloud/bigtable/client.py
  tests/unit/test_client.py
Labels: api: bigtable, cla: yes

#209 tests: harden systest further against instance creation timeout
  tests/system.py
Labels: api: bigtable, cla: yes

#214 chore(fix): cleanup old enums prior to microgen
  google/cloud/bigtable_admin_v2/gapic/enums.py
  tests/unit/test_backup.py
Labels: api: bigtable, cla: yes

#220 fix: guard assignments of certain values against None
  .gitignore
  .kokoro/build.sh
  google/cloud/bigtable_admin_v2/services/bigtable_instance_admin/client.py
  google/cloud/bigtable_admin_v2/services/bigtable_instance_admin/pagers.py
  google/cloud/bigtable_admin_v2/services/bigtable_table_admin/client.py
  google/cloud/bigtable_admin_v2/services/bigtable_table_admin/pagers.py
  google/cloud/bigtable_v2/services/bigtable/client.py
  synth.py
Labels: api: bigtable, cla: yes

#222 feat: publish new fields for CMEK
  .gitignore
  .kokoro/build.sh
  google/cloud/bigtable_admin_v2/__init__.py
  google/cloud/bigtable_admin_v2/proto/instance.proto
  google/cloud/bigtable_admin_v2/proto/table.proto
  google/cloud/bigtable_admin_v2/services/bigtable_instance_admin/async_client.py
  google/cloud/bigtable_admin_v2/services/bigtable_instance_admin/client.py
  google/cloud/bigtable_admin_v2/services/bigtable_table_admin/async_client.py
  google/cloud/bigtable_admin_v2/services/bigtable_table_admin/client.py
  google/cloud/bigtable_admin_v2/types/__init__.py
  google/cloud/bigtable_admin_v2/types/instance.py
  google/cloud/bigtable_admin_v2/types/table.py
  scripts/fixup_bigtable_admin_v2_keywords.py
  synth.metadata
  tests/unit/gapic/bigtable_admin_v2/test_bigtable_instance_admin.py
  tests/unit/gapic/bigtable_admin_v2/test_bigtable_table_admin.py
Labels: api: bigtable, cla: yes, context: partial

#228 chore: remove temp fix, set cov level to 99
  synth.py
Labels: api: bigtable, cla: yes
