Repository googleapis/python-bigtable, pull requests merged in 2022-06, with the labels that each got.

#595 fix(deps): require protobuf <4.0.0dev
  setup.py
  testing/constraints-3.6.txt
Labels: api: bigtable, size: xs

#596 docs: fix changelog header to consistent size
  CHANGELOG.md
Labels: api: bigtable, size: s

#599 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: api: bigtable, size: s

#602 fix(deps): require protobuf<4.0.0 on v1 branch
  noxfile.py
  setup.py
Labels: api: bigtable, size: xs

#590 samples: Add BigTable delete samples
  samples/snippets/README.md
  samples/snippets/deletes/deletes_snippets.py
  samples/snippets/deletes/deletes_test.py
  samples/snippets/deletes/noxfile.py
  samples/snippets/deletes/requirements-test.txt
  samples/snippets/deletes/requirements.txt
  samples/snippets/deletes/snapshots/__init__.py
  samples/snippets/deletes/snapshots/snap_deletes_test.py
Labels: api: bigtable, samples, size: l
