Repository googleapis/python-bigtable, pull requests merged in 2025-03, with the labels that each got.

#1091 chore: remove unused files
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docker/docs/requirements.in
  .kokoro/docker/docs/requirements.txt
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/requirements.in
  .kokoro/requirements.txt
Labels: api: bigtable, size: xl

#1092 fix: Allow protobuf 6.x
  setup.py
Labels: api: bigtable, size: s

#1096 feat: Implement updated execute query protocol
  google/cloud/bigtable/data/execute_query/_async/execute_query_iterator.py
  google/cloud/bigtable/data/execute_query/_byte_cursor.py
  google/cloud/bigtable/data/execute_query/_checksum.py
  google/cloud/bigtable/data/execute_query/_reader.py
  google/cloud/bigtable/data/execute_query/_sync_autogen/execute_query_iterator.py
  setup.py
  tests/unit/data/_async/test_client.py
  tests/unit/data/_sync_autogen/test_client.py
  tests/unit/data/execute_query/_async/test_query_iterator.py
  tests/unit/data/execute_query/_sync_autogen/test_query_iterator.py
  tests/unit/data/execute_query/sql_helpers.py
  tests/unit/data/execute_query/test_byte_cursor.py
  tests/unit/data/execute_query/test_checksum.py
  tests/unit/data/execute_query/test_query_result_row_reader.py
Labels: api: bigtable, size: xl

#1099 feat: Refactor Metadata, add system tests, remove preview warning
  google/cloud/bigtable/data/_async/client.py
  google/cloud/bigtable/data/_sync_autogen/client.py
  google/cloud/bigtable/data/execute_query/__init__.py
  google/cloud/bigtable/data/execute_query/_reader.py
  google/cloud/bigtable/data/execute_query/metadata.py
  tests/system/data/test_system_async.py
  tests/system/data/test_system_autogen.py
  tests/unit/data/execute_query/test_query_result_row_reader.py
Labels: api: bigtable, size: m

#1097 fix: remove setup.cfg configuration for creating universal wheels
  setup.cfg
Labels: api: bigtable, size: s
